# Generated by Django 3.2.7 on 2021-09-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixochi',
            name='frequency',
            field=models.IntegerField(choices=[(3, 'normal'), (2, 'sad'), (1, 'hungry'), (0, 'dead')], default=600000),
        ),
    ]
