# Generated by Django 3.2.7 on 2021-09-12 16:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pixochi',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('eyes', models.IntegerField()),
                ('style', models.CharField(max_length=1)),
                ('state', models.IntegerField(choices=[(3, 'normal'), (2, 'sad'), (1, 'hungry'), (0, 'dead')], default=3)),
                ('lastStateChange', models.IntegerField(default=api.models.time_ms)),
            ],
        ),
    ]
